=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_DTD/ejercicio_EmpresaElectrica.dtd
<!ELEMENT empresa (clientes | tarifas | contratos)*>
<!ATTLIST empresa nombre CDATA #FIXED "iberdrola">
<!ELEMENT clientes (#PCDATA | cliente)*>
<!ATTLIST clientes veteranos IDREFS #REQUIRED>
<!ENTITY oferta "ofertas especiales">
<!ENTITY % atributosCliente "DNI ID #REQUIRED
                            nombre CDATA #REQUIRED
                            apellidos CDATA #IMPLIED
                            telefono CDATA #IMPLIED
                            domicilio CDATA #IMPLIED">
<!ELEMENT cliente EMPTY>
<!ATTLIST cliente %atributosCliente;>
<!ELEMENT tarifas (tarifa+)>
<!ELEMENT tarifa EMPTY>
<!ATTLIST tarifa codigo ID #REQUIRED
                precio CDATA #REQUIRED
                potencia (3.30|4.00|4.50|5.00) #REQUIRED>
<!ELEMENT contratos (contrato+)>
<!ELEMENT contrato (#PCDATA)>
<!ATTLIST contrato cliente IDREF #REQUIRED
                    tarifa IDREF #REQUIRED>

=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_DTD/ejercicio_EmpresaElectrica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "ejercicio_EmpresaElectrica.dtd">

<empresa nombre="iberdrola">

    <clientes veteranos="x666 y999" > Los clientes veteranos tendran &oferta;
        <cliente DNI="x666" nombre="Tupac" apellidos="Shakur" telefono="554477" domicilio="The East Side"/>
        <cliente DNI="y999" nombre="Notorius" apellidos="BigPoppa" telefono="554477" domicilio="The East Side"/>

        
    </clientes>
    <tarifas>
        <tarifa codigo="t1" precio="36,00" potencia="3.30"/>
        <tarifa codigo="t2" precio="25,00" potencia="3.30"/>

    </tarifas>

    <contratos>

        <contrato cliente="x666" tarifa="t1"/>


    </contratos>




</empresa>
