=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_DTD/ejercicio_LosSimpsons.dtd
<!ELEMENT LosSimpsons (personaje+)>
<!ELEMENT personaje (#PCDATA | aficiones | parentesco)*>
<!ELEMENT aficiones (TV?, (skate|bici) , tirachinas?)>
<!ELEMENT TV (#PCDATA)>
<!ELEMENT skate (#PCDATA)>
<!ELEMENT bici (#PCDATA)>
<!ELEMENT tirachinas (#PCDATA)>
<!ENTITY % atributosPersonajes "nombre ID #REQUIRED">
<!ATTLIST personaje %atributosPersonajes; categoria (protagonista | secundario) #REQUIRED
                                color CDATA #FIXED "amarillo"
                                familia CDATA #IMPLIED>
                                  
<!ENTITY Rasca "Rasca y Pica">
<!ELEMENT parentesco EMPTY>
<!ATTLIST parentesco casado IDREF #IMPLIED
                     hijo IDREFS #IMPLIED>

=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_DTD/ejercicio_LosSimpsons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LosSimpsons SYSTEM "ejercicio_LosSimpsons.dtd" >

<LosSimpsons >
    <personaje  nombre="Homer" categoria="protagonista" color="amarillo" familia="Simpsons"/>
     <parentesco casado="Marge"/>
    <personaje  nombre="Marge" categoria="protagonista" color="amarillo" familia="Simpsons"/>
        <parentesco casado="Homer"/>    
            
        
    <personaje  nombre="Lisa" categoria="protagonista" color="amarillo" familia="Simpsons"/>
        <parentesco hijo="Marge Homer" />
    <personaje  nombre="Bart" categoria="protagonista" color="amarillo" familia="Simpsons">
        <parentesco hijo="Marge Homer" />
        <aficiones>
            <TV>La serie favorita de Bart es &Rasca;</TV>
            <skate>fdsnx</skate>
            <tirachinas>gtd5d</tirachinas>
        </aficiones>
    </personaje>
    
</LosSimpsons>
