=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_DTD/ejercicio_mobiliario.dtd
<!ELEMENT urbanizacion (mobiliario, desperfectos)>
<!ATTLIST urbanizacion localidad CDATA #FIXED "Lucena">
<!ELEMENT mobiliario (zona+)>
<!ELEMENT zona (farolas,papeleras,bancos,(arboles|arreates)?)*>
<!ATTLIST zona codigo ID #REQUIRED>
<!ENTITY % atributosMobiliario "cantidad CDATA #IMPLIED
                                color CDATA #IMPLIED
                                estado (mejorable|bien|roto) #REQUIRED
                                cod_Obj_roto ID #IMPLIED">
<!ENTITY % atributosPlantas "cantidad CDATA #IMPLIED
                            tipo CDATA #IMPLIED
                            estado (mejorable|bien|roto) #REQUIRED
                            cod_Planta_daÃ±ada ID #IMPLIED">                               
<!ELEMENT farolas EMPTY>
<!ATTLIST farolas %atributosMobiliario;
                tipo_bombilla (LED | FLEX | TEX) #IMPLIED >
<!ELEMENT papeleras EMPTY>
<!ATTLIST papeleras %atributosMobiliario;> 
<!ELEMENT bancos EMPTY>
<!ATTLIST bancos %atributosMobiliario;> 
<!ELEMENT arboles EMPTY>
<!ATTLIST arboles %atributosPlantas;>
<!ELEMENT arreates EMPTY>
<!ATTLIST arreates %atributosPlantas;>
<!ELEMENT desperfectos (#PCDATA|recuento)*>
<!ENTITY cuidados "cuidar nuestro pueblo">
<!ELEMENT recuento EMPTY>
<!ATTLIST recuento zona IDREF #REQUIRED
                   desperfectos IDREFS #REQUIRED>

=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_DTD/ejercicio_mobiliario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE urbanizacion SYSTEM "ejercicio_mobiliario.dtd">

<urbanizacion localidad="Lucena">

    <mobiliario>

        <zona codigo="z1">
            <farolas cantidad="50" color="gris" tipo_bombilla="LED"  estado="mejorable"/>
            <papeleras cantidad="3" color="gris" cod_Obj_roto="p1" estado="roto"/>
            <bancos cantidad="5" color="madera" cod_Obj_roto="b3" estado="roto"/>
            <arboles cantidad="3" tipo="limonero" estado="bien"/>
            
        </zona>

        <zona codigo="z2">
                <farolas cantidad="10" color="gris" tipo_bombilla="LED" cod_Obj_roto="f5" estado="roto"/>
                <papeleras cantidad="1" color="gris" estado="bien"/>
                <bancos cantidad="3" color="madera" cod_Obj_roto="b2" estado="roto"/>
         </zona>


    </mobiliario> 

    <desperfectos>Se haran los cambios necesarios para &cuidados;

        <recuento zona="z1" desperfectos="p1 b3"/>
        <recuento zona="z2" desperfectos="f5 b2"/>
        
    </desperfectos>
   
    

</urbanizacion>
