=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_XSD/ejercicios/xml-xsd-ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="concesionario" type="tipoConcesionario"/>
  <xs:complexType name="tipoConcesionario">
    <xs:sequence>
      <xs:element name="modeloCoche" type="tipoModeloCoche" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!--ELEMENTOS MODELO COCHE -->
  <xs:complexType name="tipoModeloCoche" mixed="true">
    <xs:sequence>
      <xs:element name="modeloMotor" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="idModeloCoche" type="xs:IDREFS" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="idModeloCoche" type="tipoIdCoche" use="required"/> 
    <xs:attribute name="idsRefModeloCoche" type="xs:IDREFS" use="optional"/>
  </xs:complexType>
<!-- ID DEBE CONTENER 2 LETRAS Y 3 NUM -->
  <xs:simpleType name="tipoIdCoche">
    <xs:restriction base="xs:ID">
      <xs:pattern value="[a-z]{2}[0-9]{3}"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Ejercicios_XSD/ejercicios/xml-xsd-ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xml-xsd-ejercicio4.xsd">
  <modeloCoche idModeloCoche="mc556">No disponible</modeloCoche>
  <modeloCoche idModeloCoche="mc555" idsRefModeloCoche="mc556 mc444">Este modelo tiene un motor 1.998cc 16v. de cuatro cilindros, que desarrolla una potencia de 128 CV. Dispone de cambio manual ... el consumo medio de este monovolumen es 11 a los 100 km. El precio base es de2.225.000.
    <modeloMotor idModeloCoche="mc556"></modeloMotor>
  </modeloCoche>
  <modeloCoche idModeloCoche="mc557">No disponible</modeloCoche>
  <modeloCoche idModeloCoche="mc154">No disponible</modeloCoche>
  <modeloCoche idModeloCoche="mc444" idsRefModeloCoche="mc555 mc154">Este modelo tiene un motor 2.000cc 16v. de cuatro cilindros con 128 CV. Dispone de cambio manual ... el consumo medio de este monovolumen es 11 a los 100 km. El precio base es de 2.500.000.
    <modeloMotor idModeloCoche="mc556"></modeloMotor>
  </modeloCoche>
</concesionario>
