=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Examen/examen.dtd
<!NOTATION JPG SYSTEM "image/jpeg">
<!NOTATION PNG SYSTEM "image/png">
<!ELEMENT casa (#PCDATA| zona| recuento_electrodomesticos)*>
<!ATTLIST casa duenia CDATA #FIXED "Nuria">
<!ENTITY localidad "Lucena">
<!ELEMENT zona (electrodomestico+)>
<!ATTLIST zona lugar ID #REQUIRED
                planta (1|2|3) #REQUIRED>
<!ELEMENT electrodomestico EMPTY>
<!ATTLIST electrodomestico nombre ID #REQUIRED
                           precio CDATA #IMPLIED
                           descripcion CDATA #IMPLIED
                           tienda NMTOKEN #IMPLIED
                           imagen NOTATION (JPG|PNG) #IMPLIED>
<!ELEMENT recuento_electrodomesticos (recuento*, (electrodomestico_roto|electrodomestico_nuevo)?)>                           
<!ENTITY % atributosRecuentos "planta (1|2|3) #REQUIRED
                               lugar IDREF #REQUIRED">
<!ELEMENT recuento EMPTY>
<!ATTLIST recuento %atributosRecuentos;
            electrodomesticos IDREFS #REQUIRED>           
<!ELEMENT electrodomestico_roto EMPTY>
<!ATTLIST electrodomestico_roto %atributosRecuentos;
            electrodomesticos IDREFS #REQUIRED> 
<!ELEMENT electrodomestico_nuevo EMPTY>
<!ATTLIST electrodomestico_nuevo %atributosRecuentos;
            electrodomestico ID #REQUIRED
            imagen NOTATION (JPG|PNG) #IMPLIED>

=== nuriaRZ/EjerciciosLDM/LDM/EjerciciosLDM/Examen/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casa SYSTEM "examen.dtd" >

<casa duenia="Nuria"> Yo vivo en &localidad;
    <zona planta="2" lugar="banio">
        
            <electrodomestico  nombre="lavadora" precio="300,00" tienda="Carrefour"/>
            <electrodomestico  nombre="secadora" precio="350,00"/>
        
    </zona>

    <zona planta="1" lugar="cocina">
        
                <electrodomestico nombre="lavaplatos" precio="200,00" imagen="PNG"/>
                <electrodomestico nombre="televisor" precio="450,90" descripcion="televisor 3D"/>   
        

    </zona>

    <recuento_electrodomesticos>
        <recuento planta="2" lugar="banio" electrodomesticos="lavadora secadora" />
        <electrodomestico_nuevo planta="1" lugar="cocina" electrodomestico="frigorifico" imagen="JPG"/>
        
    </recuento_electrodomesticos>
    

</casa>
